### PR TITLE
Make rich look better in legacy Windows Console

### LINKED ISSUE #3037: [BUG] Fail the show ansi styles on "cmd.exe" (also powershell)
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

Open "cmd.exe"
And input `python -m -rich`
image
It seems that it fails to show ansi styles.
image

**Platform**
<details>
<summary>Click to expand</summary>

```
┌───────────────────────── <class 'rich.console.Console'> ─────────────────────────┐
│ A high level console interface.                                                  │
│                                                                                  │
│ ┌──────────────────────────────────────────────────────────────────────────────┐ │
│ │ <console width=111 ColorSystem.WINDOWS>                                      │ │
│ └──────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                  │
│     color_system = 'windows'                                                     │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 26                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = True                                                          │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=111, height=26),             │
│                        legacy_windows=True,                                      │
│                        min_width=1,                                              │
│                        max_width=111,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=26,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=111, height=26)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 111                                                           │
└──────────────────────────────────────────────────────────────────────────────────┘
┌─── <class 'rich._windows.WindowsConsoleFeatures'> ────┐
│ Windows features available.                           │
│                                                       │
│ ┌───────────────────────────────────────────────────┐ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ └───────────────────────────────────────────────────┘ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
└───────────────────────────────────────────────────────┘
┌────── Environment Variables ───────┐
│ {                                  │
│     'TERM': None,                  │
│     'COLORTERM': None,             │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
└────────────────────────────────────┘
platform="Windows"
```

</details>

### PR DESCRIPTION
**Pull request by littlewhitecloud**
## Type of changes

- [x] Bug fix

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description
fix #3037
`Before`
image
`After`
image
Works fine on every console program who based on `cmd.exe` and `powershell.exe`

### CODE REVIEW

**Comment by littlewhitecloud** [comment]
@willmcgugan 
Actually the legacy Windows console isn't very limited in what it can render. 

If you add `os.system("")` and the legacy Windows console will show something like Windows Terminal, but missing some emojis.(maybe limit here).

**Comment by willmcgugan** [comment]
What does `os.system("")` do? I'm assuming it enables virtual terminal sequences some how, but that is not something that Rich should do automatically, since it is a global setting. Can't you add that to your app?

**Comment by littlewhitecloud** [comment]
This is a less common usage because many people don't know about it, so I thought I could add it to rich, not in my app.

**Comment by littlewhitecloud** [comment]
Maybe also fix `python -m rich.spinner shows extra lines`

**Comment by littlewhitecloud** [comment]
Here's a comparison chart.
image

**Comment by littlewhitecloud** [comment]
Also, is there any wrong thing or it supposes to be no markdown render when execute ```python -m rich.__init__```

**Review by iamannalynleynes1206 — APPROVED** [review]

**Comment by littlewhitecloud** [comment]
So

**Comment by littlewhitecloud** [comment]
@willmcgugan

**Comment by willmcgugan** [comment]
I can't accept this, because it changes the state of the terminal as a side-effect of importing. This may impact other users who weren't accepting it.

**Comment by mon** [comment]
@littlewhitecloud How did you discover this behaviour? Is it documented anywhere? I wonder if there's a way to get the same effect without clobbering the terminal state.

Supporting more control codes in legacy term is very useful for compiling a Live app to .exe using pyinstaller/nuitka, as they will run by default in cmd.exe.

**Comment by mon** [comment]
Just leaving this here for anyone that stumbles across it - if you're fine with enabling VT sequences even after you quit your Rich application (which is OK for me), and you're running on Windows 10 TH2 (v1511) or newer (which was released around 2015), then this code snippet will get you a `Console` with `legacy_windows=False` and support for bold, italics, and more colours:

```python
console = Console()

# try and force VT support, this is HUGELY useful because in cmd.exe and
# powershell, there is huge flicker and missing bold/underline otherwise
if console.legacy_windows:
    import ctypes

    from rich import console as conlib
    from rich._win32_console import (
        ENABLE_VIRTUAL_TERMINAL_PROCESSING,
        GetConsoleMode,
        GetStdHandle,
    )
    windll = ctypes.LibraryLoader(ctypes.WinDLL)

    handle = GetStdHandle()
    mode = GetConsoleMode(handle)

    mode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING

    SetConsoleMode = windll.kernel32.SetConsoleMode
    SetConsoleMode.argtypes = [
        ctypes.wintypes.HANDLE,
        ctypes.wintypes.DWORD,
    ]
    SetConsoleMode.restype = ctypes.wintypes.BOOL
    SetConsoleMode(handle, mode)

    # re-init by invalidating the console feature check from before
    conlib._windows_console_features = None
    console = Console()
```

I can imagine this would make a good PR, but I'm not sure if it should be
a) automatically applied if possible, and then some exit hook to un-apply it. I can't seem to find any exit hooks in rich, but I didn't look very hard
b) passed as an arg to `Console`, eg `try_disable_windows_legacy` or something

**Comment by littlewhitecloud** [comment]
@mon I found this in a article and it says that it will reset the teminal(cmd or powershell)

**Review by iamannalynleynes1206 — APPROVED** [review]

**Pull request closed without merging**
