### PR TITLE
Add missing `end` keyword argument to `Text.from_markup`

### PR DESCRIPTION
**Pull request by wasi-master**
## Type of changes

- [x] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Fixes https://github.com/Textualize/rich/issues/2054

### CODE REVIEW

**Comment by willmcgugan** [comment]
Would you mind adding a test for this?

**Comment by willmcgugan** [comment]
Perfect

**Comment by wasi-master** [comment]
Time to run black again

**Comment by willmcgugan** [comment]
Great, thanks!

**Pull request merged**
