### PR TITLE
Drop Python 3.6 as the minimum-supported Python version

### PR DESCRIPTION
**Pull request by davep**
Implements the requirements outlined in #2566.

### CODE REVIEW

**Comment by davep** [comment]
This would seem to 100% deserve an entry in the `CHANGELOG`; need to have a wee chat about how and when to update the CHANGELOG.

**Comment by davep** [comment]
Annoyingly I just noticed that I managed to start this branch from code that had already had https://github.com/Textualize/rich/pull/2567/commits/ce55112d2ab35a15faf8a9ac0bbe67912dac34df applied -- this wasn't my intention. This means that this PR overlaps with https://github.com/Textualize/rich/pull/2565

**Review by willmcgugan — APPROVED** [review]

**Comment by davep** [comment]
ChangeLog tweaks made as per review.

**Review by Aravind-blip — COMMENTED** [review]
Looks good. The removal of Python 3.6 support is applied consistently across CI, packaging metadata, documentation, and compatibility code. Cleanup of legacy fallbacks simplifies the implementation without changing behavior for supported versions.

**Pull request merged**
