### PR TITLE
pretty.install() fix for some objects with `_repr_*_`

### LINKED ISSUE #1717: [BUG] repr fails for pd.Series in Jupyter with pretty.install()
**Describe the bug**

image

Any pd.Series does not appear in Jupyter (both Lab and Notebook) after `pretty.install()`, but appears with `pretty.pprint()`.
This is not the case with other pandas structures.

**To Reproduce**

For copy paste purposes:

```python
from rich import pretty
pretty.install()

import pandas as pd
df = pd.DataFrame.from_records([{'a': 1, 'b': 1}, {'a': 2, 'b': 2}])
df.a  # no output

pretty.pprint(df.a)  # outputs fine
```

```
python -m rich.diagnose
python -m rich._windows
pip freeze | grep rich
```

```
╭─────────────────────── <class 'rich.console.Console'> ───────────────────────╮
│ A high level console interface.                                              │
│                                                                              │
│ ╭──────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=80 ColorSystem.TRUECOLOR>                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│     color_system = 'truecolor'                                               │
│         encoding = 'utf-8'                                                   │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w'               │
│                    encoding='utf-8'>                                         │
│           height = 24                                                        │
│    is_alt_screen = False                                                     │
│ is_dumb_terminal = False                                                     │
│   is_interactive = True                                                      │
│       is_jupyter = False                                                     │
│      is_terminal = True                                                      │
│   legacy_windows = False                                                     │
│         no_color = False                                                     │
│          options = ConsoleOptions(                                           │
│                        size=ConsoleDimensions(width=80, height=24),          │
│                        legacy_windows=False,                                 │
│                        min_width=1,                                          │
│                        max_width=80,                                         │
│                        is_terminal=True,                                     │
│                        encoding='utf-8',                                     │
│                        max_height=24,                                        │
│                        justify=None,                                         │
│                        overflow=None,                                        │
│                        no_wrap=False,                                        │
│                        highlight=None,                                       │
│                        markup=None,                                          │
│                        height=None                                           │
│                    )                                                         │
│            quiet = False                                                     │
│           record = False                                                     │
│         safe_box = True                                                      │
│             size = ConsoleDimensions(width=80, height=24)                    │
│        soft_wrap = False                                                     │
│           stderr = False                                                     │
│            style = None                                                      │
│         tab_size = 8                                                         │
│            width = 80                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
platform="Linux"
WindowsConsoleFeatures(vt=False, truecolor=False)
rich==10.14.0
```

### PR DESCRIPTION
**Pull request by darrenburns**
## Type of changes

- [x] Bug fix - Fixes #1717 
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

The issue is that Rich assumes that if a `_repr_*_` method exists on an object, then notebook will definitely render that object. 

However, notebook only supports a subset of mimetypes, and even in the case of supported mimetypes, some libraries (e.g. `pandas`) support toggling off functionality, which results in the `_repr_*_` for that mimetype returning `None`. 

For example, `pd.Series` has a `_repr_latex_` method, but by default the config for it (`"display.latex.repr"`) is switched off and so `pd.Series._repr_latex_` returns `None`. 

We need something a little finer-grained and more aware of the notebook capabilities.

For all of the mimetypes that Jupyter notebook can display, we check if the corresponding `_repr_*_` special method exists and ensure it doesn't return `None`. If it returns `None`, Rich will print it, otherwise the notebook will render it.

### CODE REVIEW

**Comment by willmcgugan** [comment]
LGTM - Could you add that to CHANGELOG.md

**Review by willmcgugan — APPROVED** [review]

**Comment by willmcgugan** [comment]
👍

**Comment by xoolive** [comment]
So cool, many thanks to you both.
However, on my side, the pd.Series now appears (:heart_on_fire:) but is not pretty printed. That's really not a big deal (better than printing nothing) but just saying... :man_shrugging:

**Comment by willmcgugan** [comment]
That's likely because pd.Series has support for advanced rendering in Jupyter. We don't want to use Rich's printing if the object already knows how to format itself.

**Comment by xoolive** [comment]
Fine with me, thanks anyway!

**Pull request merged**
