### PR TITLE
Add arrows option to rich.tree

### PR DESCRIPTION
**Pull request by tusharsadhwani**
## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Saw some arrows in another project. Looked pretty neat, so I tried adding those into rich.

<details><summary>Code snippet:</summary>

```python
from rich import print
from rich.tree import Tree

tree = Tree("my tree", guide_style="red", arrows=True)
for i in range(5):
    tree.add(f"item {i}")
print(tree)

tree = Tree("my tree", guide_style="bold", arrows=True)
for i in range(5):
    tree.add(f"item {i}")
print(tree)
```

</details>

Example output:

image

Thoughts?

### CODE REVIEW

**Comment by willmcgugan** [comment]
I've never seen trees with arrows before. Where did you see them?

**Comment by tusharsadhwani** [comment]
On twitter:
https://twitter.com/zkat__/status/1435820136326328326

**Comment by willmcgugan** [comment]
Could you add some way to specify the arrows per-node? In-fact, maybe there are other ways of terminating the guides?

**Comment by tusharsadhwani** [comment]
Yeah, I just realised that the `arrows` attribute inside `Tree.add` isn't doing what I thought it would. I'll take a look.

I'm not sure what other endings could be used. Should the guide endings be turned into an enum then? `ARROW` being one option?

**Comment by willmcgugan** [comment]
That's what I was thinking. There may be [other symbols](https://www.compart.com/en/unicode/block/U+2B00) that make sense.

**Comment by tusharsadhwani** [comment]
The only other symbol that might make sense imo is a filled circle, and even that might leave a gap on the left edge with the bold line.

**Comment by willmcgugan** [comment]
You may be right! But even so, it would be nice to specify them per node.

**Comment by tusharsadhwani** [comment]
I might have to run a debugger over the code to understand what's being rendered where. The rendering flow doesn't seem to be what I expected.

Mind if I also add some clarifying comments?

**Comment by willmcgugan** [comment]
Be my guest.

**Comment by willmcgugan** [comment]
Hi Tushar. Do you want to persevere with this one? Unless it is per-node I don't think it will be generally useful.

**Comment by tusharsadhwani** [comment]
Yeah, I want to get to this eventually. I should wrap up a few of my projects in march, hopefully then!

**Pull request closed without merging**
