### PR TITLE
Make the Console generic on the file type

### PR DESCRIPTION
**Pull request by NeilGirdhar**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [x] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

This would have saved me from having to assert on the type here: https://github.com/NeilGirdhar/tjax/commit/085a9e4ffb989b80ab236609f73e2599856138e5#diff-8d12e9756f49b99f6d43b0863bf279057e145f38b98db4c30522b1b14138bd5c

### CODE REVIEW

**Comment by willmcgugan** [comment]
I suspect this will cause typing errors for anyone who doesn't provide the generic type. And that would lead to a flood of issues.

The solution is good, but for this reason I don't think I can merge.

**Comment by NeilGirdhar** [comment]
> I suspect this will cause typing errors for anyone who doesn't provide the generic type.

It never creates type errors.  It creates warnings if the option to warn is enabled for your type checker.

And the motivation for this is actually to prevent type errors that are otherwise unavoidable.

**Comment by willmcgugan** [comment]
Errors or warnings, I'll still get issues. I think an isinstance check is the right thing to do here. Or you could use the capture API.

**Comment by NeilGirdhar** [comment]
Okay, hopefully you switch to type defaults when 3.10 is dropped then :smile:

**Pull request closed without merging**
