### PR TITLE
In Jupyter mode have the link target set to "_blank"

### PR DESCRIPTION
**Pull request by wasi-master**
## Type of changes

- [x] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Closes https://github.com/Textualize/rich/issues/1905

I've yet not updated CHANGELOG.md since I do not know which version of rich with this pr ship with, nor when the version will be released. I have not updated CONTRIBUTORS.md since I do not think this is a significant contribution. If you want I can do those.

### CODE REVIEW

**Comment by wasi-master** [comment]
I've also noticed a similar thing for exporting HTML.

https://github.com/Texualize/rich/blob/6216ee0fccb6c40fc363ae69ea353c2e77c487fb/rich/console.py#L2091

**Comment by willmcgugan** [comment]
You can start a new Unreleased section in the CHANGELOG if it's not there already.

You should add yourself to CONTRIBUTORS. The size of your contribution doesn't matter.

**Comment by wasi-master** [comment]
Okay I'll do that

**Comment by wasi-master** [comment]
@willmcgugan done!

**Comment by willmcgugan** [comment]
Thanks

**Pull request merged**
