### PR TITLE
Update Progress documentation

### PR DESCRIPTION
**Pull request by xqm32**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [x] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [X] I accept that @willmcgugan may be pedantic in the code review.

## Description

Added method to get additional arguments stored in `task.fields`.

See https://github.com/Textualize/rich/issues/205#issuecomment-668471467.

### CODE REVIEW

**Comment by willmcgugan** [comment]
That doesn't read well...

**Comment by xqm32** [comment]
> That doesn't read well...

Sorry for my poor english, but I think users of `Progress` do need it,😭It took me a long time to fit this counter-intuitive feature.

**Comment by willmcgugan** [comment]
No worries. I'll update the docs. 谢谢你

**Comment by willmcgugan** [comment]
I've updated the progress docs. Thanks for raising this.

**Pull request closed without merging**
