### PR TITLE
Indeterminate progress tracking

### PR DESCRIPTION
**Pull request by mrvkino**
## Type of changes

- [ ] Bug fix
- [x] New feature
- [x] Documentation / docstrings
- [x] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

A task tracking the progress of an indeterminate process can be done by adding `float("inf")` as a value to the `total` attribute of the `progress.add_task` method or `track` function.

This will display a pulsing progress bar. Also, columns can be updated as normal with calls to `progress.update`. The number of element completed and the time elapse will work as expected. The value for the total in columns will be `?` and any completion percentage will be calculated as `0%` or equivalent.

The new progress bar has been added in the example provided by the module `rich.progress`.

### CODE REVIEW

**Comment by mrvkino** [comment]
@azmeuk I have added the option of tracking a sequence of indeterminate length when the total is `None`. This will reuse the `float("inf")` underneath.

This should work:
```python
from itertools import cycle
from rich.progress import track

test = ["foo", "bar", "baz"]
for value in track(cycle(test), total=None):
    print(value)
```

**Comment by mrvkino** [comment]
Whit this latest round of commit. It should wrap all request for indeterminate progress tracking.

close #1054 and close #1528

**Comment by willmcgugan** [comment]
I'm afraid I can't accept the `float("inf")`. A significant number of people will find this surprising.

**Comment by mrvkino** [comment]
Do you want to do a complete removal (internally also)?

We would only support a total of `None`. I will get on it.

**Comment by mrvkino** [comment]
Updated the code to remove the `float("inf")` support.
For specific case, I convert the `None` value to `float("inf")` internally to simplify check and calculation.

If you have any comment, it will be my pleasure to change the code.

**Comment by mrvkino** [comment]
@willmcgugan, I updated the code fixed some typing issue that arose with my code and the latest commits/merges. It should be ready for review.

**Comment by willmcgugan** [comment]
We now support total=None for indeterminate progress bars.

**Pull request closed without merging**
