### PR TITLE
Add Github flavoured markdown box type

### PR DESCRIPTION
**Pull request by tonybaloney**
## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

I've been trying to find a way to printing my Rich tables as markdown so I can copy+paste them into GitHub.

This PR adds a box class that renders markdown-friendly tables, the resulting ASCII looks like:

```default
|                    Benchmark | Min     | Max     | Mean    | Min (+)         | Max (+)         | Mean (+)        |
|------------------------------|---------|---------|---------|-----------------|-----------------|-----------------|
| Sorting 3 items instead of 7 | 0.013   | 0.013   | 0.013   | 0.010 (1.3x)    | 0.010 (1.3x)    | 0.010 (1.3x)    |
```
 
Which will display in GitHub as :

|                    Benchmark | Min     | Max     | Mean    | Min (+)         | Max (+)         | Mean (+)        |
|------------------------------|---------|---------|---------|-----------------|-----------------|-----------------|
| Sorting 3 items instead of 7 | 0.013   | 0.013   | 0.013   | 0.010 (1.3x)    | 0.010 (1.3x)    | 0.010 (1.3x)    |

### CODE REVIEW

**Comment by tonybaloney** [comment]
docs/source/appendix/box.rst needs updating, but I can't see how to generate that HTML

**Comment by tonybaloney** [comment]
@willmcgugan just tried that an copied+pasted it into the RST but its all mangled when I build the docs, there might be some secret sauce to the padding?

**Comment by willmcgugan** [comment]
I think it needs `.. raw:: html` and you need to indent each line. Sorry, been a while since I did that.

If it's a PITA, maybe you could export a SVG?

**Comment by willmcgugan** [comment]
Fantastic. Thanks.

**Review by willmcgugan — APPROVED** [review]

**Pull request merged**
