### PR TITLE
Added `no_border` option to `console.print_exception`

### PR DESCRIPTION
**Pull request by t-mangoe**
## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

I added `no_border` option to `console.print_exception`.
This PR closes the issue #2936

### CODE REVIEW

**Review by iamannalynleynes1206 — APPROVED** [review]

**Comment by willmcgugan** [comment]
There may be a need for a simpler output format, but no_border is too descriptive.

A future release may have a switch that does this, and other changes.

Thanks for the PR.

**Comment by mb6852** [comment]
The boxes around the traces make it very noisy communicating with AI. It looks create for humans but gets messed up when pasting it. A flag to turn it on/off makes it easier when actively developing the code.

**Comment by vladmandic** [comment]
@willmcgugan this was a great pr in the lack of "better" solution - would have been great to include it while you look for other long-term options

**Comment by quartzar** [comment]
This is pretty much the only thing holding us back from using `rich` tracebacks right now - it just makes it horrendous to try copy&paste a traceback with all the border characters.

**Pull request closed without merging**
