### PR TITLE
Add new column object: IterationSpeedColumn

### PR DESCRIPTION
**Pull request by chthollyphile**
## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

This pull request addresses the requirement raised in discussion #926  to add a new column for the number of iterations per second.

### CODE REVIEW

**Comment by willmcgugan** [comment]
Looks good. I'd need tests for the new column. And an entry in the docs.

**Comment by chthollyphile** [comment]
done.

**Review by willmcgugan — APPROVED** [review]

**Comment by willmcgugan** [comment]
Thanks

**Comment by willmcgugan** [comment]
Had to revert this PR I'm afraid. Assigning an attribute with setattr is a deal-breaker. It doesn't play well with static type checkers, and is best avoided. Can you not store the value on the Column object?

**Pull request merged**
