### PR TITLE
Image optimizations

### PR DESCRIPTION
**Pull request by wizard-28**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [x] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Reduces image file sizes.
Details: https://github.com/wizard-28/rich/pull/2

### CODE REVIEW

**Comment by willmcgugan** [comment]
Please exclude assets dir which includes the originals.

**Comment by wizard-28** [comment]
@willmcgugan done!

**Comment by willmcgugan** [comment]
Thanks

**Comment by wizard-28** [comment]
@willmcgugan, this isn't merged.

**Review by willmcgugan — APPROVED** [review]

**Pull request merged**
