### PR TITLE
Added emojis from Emoji Versions 13,0, 13.1, 14.0 and 15.0

### PR DESCRIPTION
**Pull request by rly0nheart**
## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [x] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Added emojis from Emoji Versions 13.0, v13.1, v14.0, v15.0

## Emoji Version 13.0
Approved for release in early 2020. The final list [was announced on 2020-01-29](https://blog.emojipedia.org/117-new-emojis-in-final-list-for-2020/), with 117 new emojis arriving on major platforms throughout 2020.

### Added Emojis

[🥲 Smiling Face with Tear](https://emojipedia.org/smiling-face-with-tear/)
    [🥸 Disguised Face](https://emojipedia.org/disguised-face/)
    [🫀 Anatomical Heart](https://emojipedia.org/anatomical-heart/)
    [🫁 Lungs](https://emojipedia.org/lungs/)
    [🫂 People Hugging](https://emojipedia.org/people-hugging/)
    [🦬 Bison](https://emojipedia.org/bison/)
    [🦣 Mammoth](https://emojipedia.org/mammoth/)
    [🦫 Beaver](https://emojipedia.org/beaver/)
    [🦤 Dodo](https://emojipedia.org/dodo/)
    [🪶 Feather](https://emojipedia.org/feather/)
    [🦭 Seal](https://emojipedia.org/seal/)
    [🪲 Beetle](https://emojipedia.org/beetle/)
    [🪳 Cockroach](https://emojipedia.org/cockroach/)
    [🪰 Fly](https://emojipedia.org/fly/)
    [🪱 Worm](https://emojipedia.org/worm/)
    [🪴 Potted Plant](https://emojipedia.org/potted-plant/)
    [🫐 Blueberries](https://emojipedia.org/blueberries/)
    [🫒 Olive](https://emojipedia.org/olive/)
    [🫑 Bell Pepper](https://emojipedia.org/bell-pepper/)
    [🫓 Flatbread](https://emojipedia.org/flatbread/)
    [🫔 Tamale](https://emojipedia.org/tamale/)
    [🫕 Fondue](https://emojipedia.org/fondue/)
    [🫖 Teapot](https://emojipedia.org/teapot/)
    [🧋 Bubble Tea](https://emojipedia.org/bubble-tea/)
    [🪨 Rock](https://emojipedia.org/rock/)
    [🪵 Wood](https://emojipedia.org/wood/)
    [🛖 Hut](https://emojipedia.org/hut/)
    [🛻 Pickup Truck](https://emojipedia.org/pickup-truck/)
    [🛼 Roller Skate](https://emojipedia.org/roller-skate/)
    [🪄 Magic Wand](https://emojipedia.org/magic-wand/)
    [🪅 Piñata](https://emojipedia.org/pinata/)
    [🪆 Nesting Dolls](https://emojipedia.org/nesting-dolls/)
    [🪡 Sewing Needle](https://emojipedia.org/sewing-needle/)
    [🪢 Knot](https://emojipedia.org/knot/)
    [🩴 Thong Sandal](https://emojipedia.org/thong-sandal/)
    [🪖 Military Helmet](https://emojipedia.org/military-helmet/)
    [🪗 Accordion](https://emojipedia.org/accordion/)
    [🪘 Long Drum](https://emojipedia.org/long-drum/)
    [🪙 Coin](https://emojipedia.org/coin/)
    [🪃 Boomerang](https://emojipedia.org/boomerang/)
    [🪚 Carpentry Saw](https://emojipedia.org/carpentry-saw/)
    [🪛 Screwdriver](https://emojipedia.org/screwdriver/)
    [🪝 Hook](https://emojipedia.org/hook/)
    [🪜 Ladder](https://emojipedia.org/ladder/)
    [🛗 Elevator](https://emojipedia.org/elevator/)
    [🪞 Mirror](https://emojipedia.org/mirror/)
    [🪟 Window](https://emojipedia.org/window/)
    [🪠 Plunger](https://emojipedia.org/plunger/)
    [🪤 Mouse Trap](https://emojipedia.org/mouse-trap/)
    [🪣 Bucket](https://emojipedia.org/bucket/)
    [🪥 Toothbrush](https://emojipedia.org/toothbrush/)
    [🪦 Headstone](https://emojipedia.org/headstone/)
    [🪧 Placard](https://emojipedia.org/placard/)
    [⚧️ Transgender Symbol](https://emojipedia.org/transgender-symbol/)
   [🤌 Pinched Fingers](https://emojipedia.org/pinched-fingers/) (5 skin tone variants included)
   [🥷 Ninja](https://emojipedia.org/ninja/) (5 skin tone variants included)
    [🤵‍♂️ Man in Tuxedo](https://emojipedia.org/man-in-tuxedo/) (5 skin tone variants included)
    [🤵‍♀️ Woman in Tuxedo](https://emojipedia.org/woman-in-tuxedo/) (5 skin tone variants included)
    [👰‍♂️ Man with Veil](https://emojipedia.org/man-with-veil/) (5 skin tone variants included)
    [👰‍♀️ Woman with Veil](https://emojipedia.org/woman-with-veil/) (5 skin tone variants included)
    [👩‍🍼 Woman Feeding Baby](https://emojipedia.org/woman-feeding-baby/) (5 skin tone variants included)
    [👨‍🍼 Man Feeding Baby](https://emojipedia.org/man-feeding-baby/) (5 skin tone variants included)
    [🧑‍🍼 Person Feeding Baby](https://emojipedia.org/person-feeding-baby/) (5 skin tone variants included)
    [🐈‍⬛ Black Cat](https://emojipedia.org/black-cat/)
    [🐻‍❄️ Polar Bear](https://emojipedia.org/polar-bear/)
    [🏳️‍⚧️ Transgender Flag](https://emojipedia.org/transgender-flag/)
***

## Emoji Version 13.1
Emoji 13.1 is the set of emojis recommended for release in September 2020. Additions include mixed skin tone support for all variations of [💏 Kiss](https://emojipedia.org/kiss/) and [💑 Couple with Heart](https://emojipedia.org/couple-with-heart/), which until this release were only available in default yellow on most major platforms.

### Added Emojis
[😶‍🌫️ Face in Clouds](https://emojipedia.org/face-in-clouds/)
[😮‍💨 Face Exhaling](https://emojipedia.org/face-exhaling/)
[😵‍💫 Face with Spiral Eyes](https://emojipedia.org/face-with-spiral-eyes/)
[❤️‍🔥 Heart on Fire](https://emojipedia.org/heart-on-fire/)
[❤️‍🩹 Mending Heart](https://emojipedia.org/mending-heart/)
[🧔‍♂️ Man: Beard](https://emojipedia.org/man-beard/) (5 skin tone variants included)
[🧔‍♀️ Woman: Beard](https://emojipedia.org/woman-beard/) (5 skin tone variants included)
***

## Emoji Version 14.0
Emoji 14.0 is the latest set of emojis recommended for release, approved September 14, 2021 alongside [Unicode 14.0](https://emojipedia.org/unicode-14.0/).

Additions include mixed skin tone support for [🤝 Handshake](https://emojipedia.org/handshake/), which until now has been only default yellow on most major platforms. Other new emojis include a [saluting face](https://emojipedia.org/saluting-face/), a [mirrored disco ball](https://emojipedia.org/mirror-ball/), and [biting lip](https://emojipedia.org/biting-lip/).

### Added Emojis
[🫠 Melting Face](https://emojipedia.org/melting-face/)
    [🫢 Face with Open Eyes and Hand Over Mouth](https://emojipedia.org/face-with-open-eyes-and-hand-over-mouth/)
    [🫣 Face with Peeking Eye](https://emojipedia.org/face-with-peeking-eye/)
    [🫡 Saluting Face](https://emojipedia.org/saluting-face/)
    [🫥 Dotted Line Face](https://emojipedia.org/dotted-line-face/)
    [🫤 Face with Diagonal Mouth](https://emojipedia.org/face-with-diagonal-mouth/)
    [🥹 Face Holding Back Tears](https://emojipedia.org/face-holding-back-tears/)
    [🫱 Rightwards Hand](https://emojipedia.org/rightwards-hand/) (5 skin tone variants included)
    [🫲 Leftwards Hand](https://emojipedia.org/leftwards-hand/) (5 skin tone variants included)
    [🫳 Palm Down Hand](https://emojipedia.org/palm-down-hand/) (5 skin tone variants included)
    [🫴 Palm Up Hand](https://emojipedia.org/palm-up-hand/) (5 skin tone variants included)
    [🫰 Hand with Index Finger and Thumb Crossed](https://emojipedia.org/hand-with-index-finger-and-thumb-crossed/) (5 skin tone variants included)
    [🫵 Index Pointing at the Viewer](https://emojipedia.org/index-pointing-at-the-viewer/) (5 skin tone variants included)
    [🫶 Heart Hands](https://emojipedia.org/heart-hands/) (5 skin tone variants included)
    [🫦 Biting Lip](https://emojipedia.org/biting-lip/)
    [🫅 Person with Crown](https://emojipedia.org/person-with-crown/) (5 skin tone variants included)
    [🫃 Pregnant Man](https://emojipedia.org/pregnant-man/) (5 skin tone variants included)
    [🫄 Pregnant Person](https://emojipedia.org/pregnant-person/) (5 skin tone variants included)
    [🧌 Troll](https://emojipedia.org/troll/)
    [🪸 Coral](https://emojipedia.org/coral/)
    [🪷 Lotus](https://emojipedia.org/lotus/)
    [🪹 Empty Nest](https://emojipedia.org/empty-nest/)
    [🪺 Nest with Eggs](https://emojipedia.org/nest-with-eggs/)
    [🫘 Beans](https://emojipedia.org/beans/)
    [🫗 Pouring Liquid](https://emojipedia.org/pouring-liquid/)
    [🫙 Jar](https://emojipedia.org/jar/)
    [🛝 Playground Slide](https://emojipedia.org/playground-slide/)
    [🛞 Wheel](https://emojipedia.org/wheel/)
    [🛟 Ring Buoy](https://emojipedia.org/ring-buoy/)
    [🪬 Hamsa](https://emojipedia.org/hamsa/)
    [🪩 Mirror Ball](https://emojipedia.org/mirror-ball/)
    [🪫 Low Battery](https://emojipedia.org/low-battery/)
    [🩼 Crutch](https://emojipedia.org/crutch/)
    [🩻 X-Ray](https://emojipedia.org/x-ray/)
    [🫧 Bubbles](https://emojipedia.org/bubbles/)
    [🪪 Identification Card](https://emojipedia.org/identification-card/)
    [🟰 Heavy Equals Sign](https://emojipedia.org/heavy-equals-sign/)
***

## Emoji Version 15.0
Emoji 15.0 is the latest set of emojis recommended for release, approved September 13, 2022 alongside [Unicode 15.0](https://emojipedia.org/unicode-15.0/).

### Added Emojis
[🫨 Shaking Face](https://emojipedia.org/shaking-face/)
    [🩷 Pink Heart](https://emojipedia.org/pink-heart/)
    [🩵 Light Blue Heart](https://emojipedia.org/light-blue-heart/)
    [🩶 Grey Heart](https://emojipedia.org/grey-heart/)
    [🫏 Donkey](https://emojipedia.org/donkey/)
    [🫎 Moose](https://emojipedia.org/moose/)
    [🪿 Goose](https://emojipedia.org/goose/)
    [🪽 Wing](https://emojipedia.org/wing/)
    [🪼 Jellyfish](https://emojipedia.org/jellyfish/)
    [🪻 Hyacinth](https://emojipedia.org/hyacinth/)
    [🫛 Pea Pod](https://emojipedia.org/pea-pod/)
    [🫚 Ginger](https://emojipedia.org/ginger/)
    [🪭 Folding Hand Fan](https://emojipedia.org/folding-hand-fan/)
    [🪮 Hair Pick](https://emojipedia.org/hair-pick/)
    [🪈 Flute](https://emojipedia.org/flute/)
    [🪇 Maracas](https://emojipedia.org/maracas/)
    [🪯 Khanda](https://emojipedia.org/khanda/)
    [🛜 Wireless](https://emojipedia.org/wireless/)
    [🫸 Rightwards Pushing Hand](https://emojipedia.org/rightwards-pushing-hand/) (5 skin tone variants included)
    [🫷 Leftwards Pushing Hand](https://emojipedia.org/leftwards-pushing-hand/) (5 skin tone variants included)
    [🐦‍⬛ Black Bird](https://emojipedia.org/black-bird/)
***

### CODE REVIEW

**Review by iamannalynleynes1206 — APPROVED** [review]

**Comment by pkulev** [comment]
When? 🙏

**Comment by rly0nheart** [comment]
> When? 🤌  🙏 

By 'when' you mean when did I make these changes?😅

**Comment by rly0nheart** [comment]
> No, I mean when it will be merged and new version released 😆 I really need the "pinched fingers" for my big development tool at my work 😅 

Oh I honestly don't know. There have been recent releases of Rich but this has not been merged yet.

That being said, I developed my own Emoji Library, you can take a look at it and use that in your project if you want [Glyphoji](https://pypi.org/project/glyphoji)

**Comment by otteydw** [comment]
This would be great!   I was looking to use 🪨 and noticed it didn't work in rich. 😦

**Comment by rly0nheart** [comment]
> This would be great!   I was looking to use 🪨 and noticed it didn't work in rich. 😦 

You can find it in [glyphoji](https://github.com/rly0nheart/glyphoji) by using `glyph.rock`. 
Example:

```python
from glyphoji import glyph

print(glyph.rock)
```

**Comment by pkulev** [comment]
> you can take a look at it and use that in your project if you want [Glyphoji](https://pypi.org/project/glyphoji)

Unfortunately, it seems I can't. I use rich_click for having rich markup in click handler docstings and this works really well. Maybe if there were such thing as f-docstring;-)

Example of one subcommand:
Screenshot_20231015-072440_Termux

**Pull request closed without merging**
