### PR TITLE
fix: bug: IPython environment undetection in `pretty.install()`

### LINKED ISSUE #2888: [BUG] rich v13.3.2 pretty.install not working in IPython
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

In IPython,

``` python
from rich import pretty
pretty.install()
```

fail to work:

screenshot1

In the original Python Interpreter, it works fine.

**It seems that only `rich=13.3.2` has this issue. `rich=13.3.1` works fine on my end.**

**Platform**
<details>
<summary>Click to expand</summary>

I'm running on Elementary OS. This issue also appears on Windows and WSL in Windows Terminal.

```
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=177 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 47                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=177, height=47),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=177,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=47,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=177, height=47)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 177                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-256color',      │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Linux"
rich @ file:///home/conda/feedstock_root/build_artifacts/rich-split_1677956885701/work/dist
```

</details>

### PR DESCRIPTION
**Pull request by xsjk**
## Type of changes

- [x] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Fix #2888 by replacing `if "get_ipython" in globals():` to `if hasattr(builtins, "get_ipython")` in `pretty.install()`

In the previous release v13.3.1, the detection of ipython environment was implemented by try-except:
```Python
try:
    ip = get_ipython()
```
And in current release v13.3.2, the detection is implemented by if-else:
```Python
if "get_ipython" in globals():
    ip = get_ipython()
```
However, since different files has different `globals()`, the method `get_ipython` is not in `globals()` of pretty.py thoungh it is in `globals()` of the IPython command line. The method can be accessed by pretty.py only because it was added to `builtins` which is shared among files. Revert back to the implementation in v13.3.1 will fix the undetection problem, or we could change `globals()` to `__builtins__`:
```Python
# if "get_ipython" in __builtins__:
if hasattr(builtins, "get_ipython"):
    ip = get_ipython()
```

### CODE REVIEW

**Comment by sshishov** [comment]
This is the original bug: https://github.com/Textualize/rich/issues/2866

**Comment by uuip** [comment]
@willmcgugan @xsjk  Could someone follow this pr or resolve 
@cilki  commit https://github.com/Textualize/rich/commit/9692794b88e352643088c6661ad06d9be6d6061f lead to bug  https://github.com/Textualize/rich/issues/2866

**Comment by cilki** [comment]
Oops, sorry to cause this! Can confirm the requested change also works with nuitka.

**Comment by willmcgugan** [comment]
Closing, assumed stale.

**Pull request closed without merging**
