### PR TITLE
don't break 'pip inspect' on windows console

### PR DESCRIPTION
**Pull request by stonebig**
see https://github.com/pypa/pip/issues/11798

## Type of changes

- [x] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Please describe your changes here. If this fixes a bug, please link to the issue, if possible.

### CODE REVIEW

**Comment by stonebig** [comment]
it's an ugly but simple patch to solve my problem without loosing 'pip inspect' functionality, on windows console.

**Comment by The-Codester-Vs** [comment]
Use powershell console 

pip freeze | %{$_.split('==')[0]} | %{pip install --upgrade $_} 

May be it work.

**Comment by stonebig** [comment]
> Use powershell console
> 
> pip freeze | %{$_.split('==')[0]} | %{pip install --upgrade $_}
> 
> May be it work.

I did try with powershell console, but maybe there is still some cp1252 hidden in it.

**Comment by The-Codester-Vs** [comment]
It may be help 

https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/pypa/pip/issues/9573&ved=2ahUKEwi5-8qXrJD9AhUe3jgGHVD5DUwQFnoECAoQAQ&usg=AOvVaw02xy-2H_8e-rTD8jNBnQUB

**Comment by stonebig** [comment]
will try the `PYTHONIOENCODING="utf-8"` suggested per @willmcgugan

**Pull request closed without merging**
