### PR TITLE
Allow tilde in URL (fixes #3057)

### LINKED ISSUE #3057: [BUG] Tilde not included in link regex
The following doesn't highlight pas the `~`
```
>>> from rich import print
>>> print("http://127.0.0.1/~foo")
http://127.0.0.1/~foo
```

### PR DESCRIPTION
**Pull request by LukeSavefrogs**
This PR fixes #3057.

## Type of changes

- [X] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [x] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [X] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I've added tests for new code.
- [X] I accept that @willmcgugan may be pedantic in the code review.

## Description

Please describe your changes here. If this fixes a bug, please link to the issue, if possible.

### CODE REVIEW

**Comment by willmcgugan** [comment]
Thanks. Can you add test(s)  please.

**Comment by LukeSavefrogs** [comment]
> Thanks. Can you add test(s) please.

I can, do you think it's actually needed? It's literally one character in the regex and I don't see tests for other special characters (for example `%`, `$`, `+` and so on). 

Just asking anyway, it's not a problem adding an extra line in the tests 😄

**Comment by willmcgugan** [comment]
You are probably correct, but a regression test is better than "probably".

**Comment by LukeSavefrogs** [comment]
> You are probably correct, but a regression test is better than "probably".

I agree

If you're ok then I'll add the missing tests too, then (like `https://example.org/index.html?param1=value1`) 😀

**Comment by willmcgugan** [comment]
Couldn’t hurt!

**Comment by LukeSavefrogs** [comment]
Done 😀

**Review by willmcgugan — APPROVED** [review]
LGTM

**Comment by LukeSavefrogs** [comment]
Forgot to run `black` to change formatting, so I did that just now. 😅

Anyway... Running `make format-check` shows that there are a lot of files (30) that should be formatted as well:

image

**Pull request merged**
