### PR TITLE
bump typing extension

### PR DESCRIPTION
**Pull request by willmcgugan**
Fixes dependancy issue https://github.com/Textualize/rich/issues/2150

### CODE REVIEW

**Comment by cschlittPHI** [comment]
Is there any way to bump the version number from this? We can't seem to use it as it uses the old version number still I think?

**Comment by willmcgugan** [comment]
New release coming soon

**Comment by willmcgugan** [comment]
@henryiii FYI we had to bump typing-extensions because the minimum version didn't have OrderedDict

**Comment by henryiii** [comment]
That's annoying, very sorry! According to https://github.com/python/typing/tree/master/typing_extensions it was added in 3.7. They don't have a proper changelog until "4.0", so it can be hard to tell what's in typing_extensions, so I thought it was in typing_extensions 3.7 too. Looking at the history, it was added in 3.10.0 in https://github.com/python/typing/commit/ea7f88e8d2dd28a5569b2385c21b17063c480c7f Please feel free to ping me if you need any help with anything related to what I've done.

In build we test all minimum versions too: https://github.com/pypa/build/blob/main/tests/constraints.txt (ironically, except for `typing_extensons`). I can set up a test like that if you want one.

**Pull request merged**
