### PR TITLE
Fix CHANGELOG.md

### PR DESCRIPTION
**Pull request by rodrigogiraoserrao**
## Type of changes

- [x] Documentation

## Checklist

- [x] I accept that @willmcgugan may be pedantic in the ~~code~~ review.

## Description

The changelog had missing/wrong compare links for most recent and oldest versions.
I see some compare links are present even if the underlying tags were not created, so I followed this style and created all links as if the tags existed.

### CODE REVIEW

**Comment by rodrigogiraoserrao** [comment]
Checking why the MacOS on Py3.11 failed, and it doesn't look like it's this PR's fault, but maybe I misunderstood the error.

**Comment by willmcgugan** [comment]
Yeah, looks environment related. Will try a rerun.

**Comment by rodrigogiraoserrao** [comment]
The Mac build passed after your rerun, so it does look like it was env related.
Who's at fault, here..?

**Comment by willmcgugan** [comment]
Beats me. We do have some integration tests which may suffer from race conditions. One of the pains of concurrent programming.

Unrelated to this PR though!

**Comment by willmcgugan** [comment]
obrigado

**Comment by rodrigogiraoserrao** [comment]
De nada.
I think you need to approve before this gets auto-merged 🙃

**Review by willmcgugan — APPROVED** [review]

**Pull request merged**
