### PR TITLE
Pycln QA tool as a pre-commit hook

### PR DESCRIPTION
**Pull request by hadialqattan**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [x] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate. (not needed for this PR)
- [ ] I've added tests for new code. (not needed for this PR)
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

I saw `pycln` (which is a formatter for finding and removing unused import statements) a good addition to the current pre-commit hooks which I believe would ensure a high code quality standard besides `black` and `isort`. 

BTW, I'm the author of `pycln` 😄.

Anyway, please feel free to ask any questions and/or reject/close this PR.

\+ I would like to thank you for inventing this incredible library!

### CODE REVIEW

**Comment by willmcgugan** [comment]
It's a good idea! Do you have examples of other notable projects using pycln

**Comment by hadialqattan** [comment]
> It's a good idea! Do you have examples of other notable projects using pycln

For now,  [fossasia's open event server](https://github.com/fossasia/open-event-server/) is the most notable project that I can name.

Also, someone ran `pycln` against `poetry` in this [PR](https://github.com/python-poetry/poetry/pull/5088) then one of the `poetry` maintainers/active contributors said:
>A second PR adding `pycln` to the pre-commit config would be welcome, I think.
>
>Consensus seems to be that the new Union syntax is harmless and nicer to write. Let's go ahead with this.
>
>_Originally posted by @neersighted in https://github.com/python-poetry/poetry/issues/5088#issuecomment-1020796731_

therefore I've created a [PR](https://github.com/python-poetry/poetry/pull/5234) in `poetry` to add `pycln` to their pre-commit hooks and it's about to be merged.

---
In fact, in the last few days I offered Pycln to several mainstream projects so maybe in the next few weeks we will see more notable projects using it.

**Comment by henryiii** [comment]
I've included pycln in the [Scikit-HEP developer pages](https://scikit-hep.org/developer/style) for a while, so projects that follow that sometimes use it, like https://github.com/pybind/pybind11, https://github.com/pyodide/pyodide, https://github.com/pypa/cibuildwheel, and of course a few Scikit-HEP libraries. My favorite is likely Pyodide's usage, as it's a great manual hook - running it by default can be a little overkill (a typo when using a library can cause that library to be removed, for example), but it's really handy during refactors, like `from __future__ import annotations` additions, etc.

**Comment by hadialqattan** [comment]
> I've included pycln in the [Scikit-HEP developer pages](https://scikit-hep.org/developer/style) for a while, so projects that follow that sometimes use it, like https://github.com/pybind/pybind11, https://github.com/pyodide/pyodide, https://github.com/pypa/cibuildwheel, and of course a few Scikit-HEP libraries. My favorite is likely Pyodide's usage, as it's a great manual hook - running it by default can be a little overkill (a typo when using a library can cause that library to be removed, for example), but it's really handy during refactors, like `from __future__ import annotations` additions, etc.

That's awesome, actually, I already know that those projects use Pycln, but I forgot about them for some reason...Anyway thanks a lot @henryiii for supporting Pycln and using it.

**Comment by hadialqattan** [comment]
> It's a good idea! Do you have examples of other notable projects using pycln

I have included a [used by](https://github.com/hadialqattan/pycln#used-by) section in the README file containing a list of notable projects/organizations that use _Pycln_.

**Comment by willmcgugan** [comment]
@hadialqattan Ok, let's give it a go :)

I created a merge conflict for you. Would you mind fixing that and I'll merge?

**Comment by hadialqattan** [comment]
> @hadialqattan Ok, let's give it a go :)
> 
> I created a merge conflict for you. Would you mind fixing that and I'll merge?

I've fixed it, but please let me double check my work again.

**Review by willmcgugan — APPROVED** [review]

**Comment by hadialqattan** [comment]
Now we are good to go 👍🏻

**Comment by hadialqattan** [comment]
btw, sorry for bothering you with my recent commits which triggers workflows approval request over and over again.

**Comment by willmcgugan** [comment]
THanks.

**Comment by willmcgugan** [comment]
I was worried about this. The PR broke the IPython extension. Is there any way to tell it not to touch a given import?

**Comment by hadialqattan** [comment]
> I was worried about this. The PR broke the IPython extension. Is there any way to tell it not to touch a given import?

Yes, of course, please take a look at the [Pycln skips](https://hadialqattan.github.io/pycln/#/?id=pycln-skips) section. 

btw, @henryiii has already fixed it in #2109.

**Comment by hadialqattan** [comment]
In case you wanna know why Pycln didn't treat it as used by default:  (we are already using the `--all` flag)
- [side effects](https://hadialqattan.github.io/pycln/#/?id=side-effects)
- [--all flag](https://hadialqattan.github.io/pycln/#/?id=-a-all-flag)

btw, not using the `--all` flag seems safer but I encourage using it because the false-positive cases usually occur much more than the false-negative ones. Also, it's easier to spot and correct the false-negative ones.

**Pull request merged**
